apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: all-secrets
  namespace: nginx-yasin
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: my-vault
  target:
    name: all-vault-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: taha/config