apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: my-vault
  namespace: nginx-yasin
spec:
  provider:
    vault:
      server: http://vault.vault.svc.cluster.local:8200
      path: secret
      version: v2
      auth:
        userPass:
          username: taha	
          secretRef:
            name: vault-taha-user-pass
            key: pass
          path: userpass